# Creating Ontology of 311 Park Names -> official park names

This notebook creates a match dictionary between park names in 311 data and in NYC Parks official dataset. 
Using this dictionary we can match each park-related call to specific park or park District

Here I am using [fuzzywuzzy module](https://github.com/seatgeek/fuzzywuzzy)

In [152]:
__author__ = "Philipp Kats"
__date__ = "2015_10_15"

import pandas as pd
import geopandas as gp
import numpy as np
import os
from fuzzywuzzy import process  ## fuzzy string match in python

%pylab inline
PARQA = os.getenv('PARQA') #basic path

Populating the interactive namespace from numpy and matplotlib

need to add: recreation centers,
    todd lot, and remove PS

## Getting 311 Data

In [153]:
calls = pd.read_csv(PARQA + '/data/311DPR.csv',encoding='utf8', na_values='Unspecified')
calls= calls[pd.notnull(calls['Park Facility Name'])]

In [154]:
callParks = calls[['Park Facility Name','Borough']].drop_duplicates()
calls[pd.notnull(calls['Park Facility Name'])]
callParks['cleanName'] = callParks['Park Facility Name'].str.lower()
print '311_call_names total:', len(callParks['Park Facility Name'])

311_call_names total: 1666

In [155]:
callParks.head()

,Park Facility Name,Borough,cleanName
1,Geo Soilan Park - Battery Park City,MANHATTAN,geo soilan park - battery park city
2,Brookville Park,QUEENS,brookville park
5,Highland Park,BROOKLYN,highland park
10,Prospect Park - East Parade Grounds,BROOKLYN,prospect park - east parade grounds
11,Central Park - East 96th Street Playground,MANHATTAN,central park - east 96th street playground

In [156]:
borrowCode = pd.DataFrame({'Borough':['BROOKLYN',
                                      'QUEENS',
                                      'MANHATTAN',
                                      'BRONX',
                                      'STATEN ISLAND',
                                      'Unspecified'],
                           'code':['B',
                                   'Q',
                                   'M',
                                   'X',
                                   'R',
                                   '?']})

callParks = callParks.merge(borrowCode, how='left', on='Borough')
callParks.head(3)

,Park Facility Name,Borough,cleanName,code
0,Geo Soilan Park - Battery Park City,MANHATTAN,geo soilan park - battery park city,M
1,Brookville Park,QUEENS,brookville park,Q
2,Highland Park,BROOKLYN,highland park,B

## Getting Park names

In [157]:
## using geojson produced of OPEN DATA 
parkNames = gp.read_file(PARQA + 'data/parks_computed.geojson')[['SIGNNAME','BOROUGH']].drop_duplicates()
parkNames['SIGNNAME'] = parkNames['SIGNNAME'].str.lower()
len(parkNames['SIGNNAME'].drop_duplicates())

1787

In [158]:
#create a dictionary of parks for each borough 
#that will add accuracy and boost spead of search ( I hope)

ofParks = {k:[unicode(x) for x in list(v)] for k,v in parkNames.groupby("BOROUGH")["SIGNNAME"]}

tmp = []
for v in ofParks.values():
    tmp.extend(v)
ofParks['?'] = tmp   #['???'] ### to mark parks with unspecified Borough

print ofParks.keys()

[u'B', u'M', u'Q', u'R', u'X', '?']

In [159]:
# ofParks['B']

## I. Direct matching

In [160]:
cParksMatched = callParks.merge(parkNames, how='left', left_on = 'cleanName', right_on='SIGNNAME', copy=1)
cParksMatched['Type'] = np.nan

In [161]:
len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)])

714

In [162]:
cParksMatched.ix[(pd.notnull(cParksMatched.SIGNNAME)&pd.isnull(cParksMatched.Type)), 'Type'] = 'park_direct'

In [163]:
cParksMatched.head()

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type
0,Geo Soilan Park - Battery Park City,MANHATTAN,geo soilan park - battery park city,M,NaN,NaN,NaN
1,Brookville Park,QUEENS,brookville park,Q,brookville park,Q,park_direct
2,Highland Park,BROOKLYN,highland park,B,highland park,B,park_direct
3,Highland Park,BROOKLYN,highland park,B,highland park,Q,park_direct
4,Prospect Park - East Parade Grounds,BROOKLYN,prospect park - east parade grounds,B,NaN,NaN,NaN

## II. Empiric decoding

In [164]:
#some manual improvisation, based on emirical experience

def empiric(x):
    'recognition, based on emirical experience'
    general = {'flushing meadows':'flushing meadows and corona park',
               'central park':'central park', 
               'prospect park':'prospect park',
               'greenbelt': 'greenbelt native plant center',
               'red hook park':'red hook recreation area',
               'crotona park':'crotona park',
               'marine park': 'marine park', 
               'van cortlandt':'van cortlandt park',
               'seravalli': 'corporal john a. seravalli playground',
               'inwood hill': 'inwood hill park',
               'forest park':'forest park',
               'pelham bay park':'pelham bay park',
               'kissena park': 'kissena park',
               'asser levy': 'asser levy park',
               'highland park':'highland park',
               'bronx park':'bronx park',
               '100 percent':'100% Playground',
               'seaside playground':'Seaside Playground'
                }
    
    
    for k in general.keys():
        if k in x.cleanName:
            return general[k]
    return np.nan

In [165]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME), 'SIGNNAME'] = cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME)].apply(empiric,1)

In [166]:
cParksMatched.ix[(pd.notnull(cParksMatched.SIGNNAME)&pd.isnull(cParksMatched.Type)), 'Type'] = 'empiric'

In [167]:
cParksMatched.head(10)

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type
0,Geo Soilan Park - Battery Park City,MANHATTAN,geo soilan park - battery park city,M,NaN,NaN,NaN
1,Brookville Park,QUEENS,brookville park,Q,brookville park,Q,park_direct
2,Highland Park,BROOKLYN,highland park,B,highland park,B,park_direct
3,Highland Park,BROOKLYN,highland park,B,highland park,Q,park_direct
4,Prospect Park - East Parade Grounds,BROOKLYN,prospect park - east parade grounds,B,prospect park,NaN,empiric
5,Central Park - East 96th Street Playground,MANHATTAN,central park - east 96th street playground,M,central park,NaN,empiric
6,Washington Hall Park,BROOKLYN,washington hall park,B,washington hall park,B,park_direct
7,Callahan-Kelly Playground,BROOKLYN,callahan-kelly playground,B,callahan-kelly playground,B,park_direct
8,William H Seward Park,MANHATTAN,william h seward park,M,NaN,NaN,NaN
9,Col David Marcus Playground,BROOKLYN,col david marcus playground,B,NaN,NaN,NaN

In [168]:
print 'Recognized:'
print len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)]), '/', len(cParksMatched)

Recognized:
923 / 1678

## III. Playgrounds

In [169]:
playgrounds = [x.decode('utf8') for x in pd.read_csv(PARQA + 'data/DPR_property/playgrounds.csv')['Name'].tolist()]

In [170]:
# cParksMatched[pd.isnull(cParksMatched.SIGNNAME)][cParksMatched.cleanName.str.contains('play')]

In [171]:
cParksMatched['match'] = np.nan
cParksMatched['ratio'] = np.nan

In [172]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('play'), 'Type'] = 'pgs'
cParksMatched.ix[cParksMatched.Type=='pgs', 'match'] = \
cParksMatched.ix[cParksMatched.Type=='pgs', 'cleanName'].apply(lambda x: process.extractOne(x, playgrounds))

In [173]:
cParksMatched.ix[cParksMatched.Type=='pgs', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='pgs', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='pgs', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='pgs', 'match'].apply(lambda x: x[1])

In [174]:
cParksMatched[cParksMatched.Type=='pgs']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
9,Col David Marcus Playground,BROOKLYN,col david marcus playground,B,Col David Marcus Mem Playground,NaN,pgs,"(Col David Marcus Mem Playground, 95)",95
13,Mccarren Park - Vincent V Abate Playground,BROOKLYN,mccarren park - vincent v abate playground,B,Vincent V Abate Playground,NaN,pgs,"(Vincent V Abate Playground, 90)",90
24,Harold L Ickes Playground,BROOKLYN,harold l ickes playground,B,Harold Ickes Playground,NaN,pgs,"(Harold Ickes Playground, 96)",96
27,Hoover Manton Playground,QUEENS,hoover manton playground,Q,Manton Playground,NaN,pgs,"(Manton Playground, 95)",95
33,Emerald Playground - PS 200,QUEENS,emerald playground - ps 200,Q,Playground,NaN,pgs,"(Playground, 90)",90
36,Doctor Gertrude B Kelly Playground,MANHATTAN,doctor gertrude b kelly playground,M,Dr Gertrude B Kelly Playground,NaN,pgs,"(Dr Gertrude B Kelly Playground, 94)",94
46,May Matthews Playground,MANHATTAN,may matthews playground,M,May Matthews Playground,NaN,pgs,"(May Matthews Playground, 100)",100
47,Cuyler Gore Playground,BROOKLYN,cuyler gore playground,B,Cuyler Gore,NaN,pgs,"(Cuyler Gore, 90)",90
52,Terrapin Playground - JHS 51,BROOKLYN,terrapin playground - jhs 51,B,Terrapin Playground,NaN,pgs,"(Terrapin Playground, 95)",95
53,Jamaica Playground - PS 40,QUEENS,jamaica playground - ps 40,Q,Jamaica Playground (ps 40),NaN,pgs,"(Jamaica Playground (ps 40), 98)",98
56,Hancock Playground,BROOKLYN,hancock playground,B,Hancock Playground,NaN,pgs,"(Hancock Playground, 100)",100
68,Bath Beach Playground,BROOKLYN,bath beach playground,B,Bath Beach Playground,NaN,pgs,"(Bath Beach Playground, 100)",100
75,Queens Valley Playground - PS 164,QUEENS,queens valley playground - ps 164,Q,Queens Valley Playground,NaN,pgs,"(Queens Valley Playground, 95)",95
76,Sumner Playground - PS 59,BROOKLYN,sumner playground - ps 59,B,Sumner Playground,NaN,pgs,"(Sumner Playground, 95)",95
82,Riverside Park - Claremont Playground,MANHATTAN,riverside park - claremont playground,M,Claremont,NaN,pgs,"(Claremont, 90)",90
95,Mount Playground - PS 174,QUEENS,mount playground - ps 174,Q,Playground,NaN,pgs,"(Playground, 90)",90
110,Russell Pederson Playground,BROOKLYN,russell pederson playground,B,Russell Pederson Playground,NaN,pgs,"(Russell Pederson Playground, 100)",100
112,Sol Bloom Playground,MANHATTAN,sol bloom playground,M,Sol Bloom Playground,NaN,pgs,"(Sol Bloom Playground, 98)",98
113,Cabbell Park and Cambria Playground,QUEENS,cabbell park and cambria playground,Q,Playground,NaN,pgs,"(Playground, 90)",90
114,Booker T Washington Playground,MANHATTAN,booker t washington playground,M,Booker T Washington Playground,NaN,pgs,"(Booker T Washington Playground, 100)",100
126,Midland Beach - Playland Playground,STATEN ISLAND,midland beach - playland playground,R,Midland Beach Playground,NaN,pgs,"(Midland Beach Playground, 95)",95
129,Pool - PS 186 Playground,QUEENS,pool - ps 186 playground,Q,Playground,NaN,pgs,"(Playground, 90)",90
131,Dr Richard Green Playground,BROOKLYN,dr richard green playground,B,Dr Richard Green Playground,NaN,pgs,"(Dr Richard Green Playground, 100)",100
132,East River Playground - PS 146,MANHATTAN,east river playground - ps 146,M,East River Playground,NaN,pgs,"(East River Playground, 95)",95
147,Jamie Campiz Playground,BROOKLYN,jamie campiz playground,B,Jaime Campiz Playground,NaN,pgs,"(Jaime Campiz Playground, 96)",96
153,Riverside Park - River Run Playground,MANHATTAN,riverside park - river run playground,M,River Run Playground,NaN,pgs,"(River Run Playground, 90)",90
155,Morton Playground,BRONX,morton playground,X,Morton Playground,NaN,pgs,"(Morton Playground, 100)",100
157,Mosholu Playground - PS 8,BRONX,mosholu playground - ps 8,X,Playground,NaN,pgs,"(Playground, 90)",90
163,Riverdale Playground - JHS 141,BRONX,riverdale playground - jhs 141,X,Playground,NaN,pgs,"(Playground, 90)",90
170,Jackie Robinson Park - Playground One Fifty Tw...,MANHATTAN,jackie robinson park - playground one fifty tw...,M,Jackie Robinson Park,NaN,pgs,"(Jackie Robinson Park, 90)",90
...,...,...,...,...,...,...,...,...,...
1511,Playground 103,MANHATTAN,playground 103,M,Playground 103 CIII,NaN,pgs,"(Playground 103 CIII, 95)",95
1514,Seven Gables Playground - IS 74,QUEENS,seven gables playground - is 74,Q,Seven Gables Playground,NaN,pgs,"(Seven Gables Playground, 95)",95
1520,PS 125 Playground,BROOKLYN,ps 125 playground,B,Ps 125 Playground,NaN,pgs,"(Ps 125 Playground, 100)",100
1538,146 St Playground,QUEENS,146 st playground,Q,Playground 146,NaN,pgs,"(Playground 146, 95)",95
1545,De Salvio Playground,MANHATTAN,de salvio playground,M,Desalvio Playground,NaN,pgs,"(Desalvio Playground, 97)",97
1559,Pool - Mariners Harbor Playground,STATEN ISLAND,pool - mariners harbor playground,R,Mariners Harbor Playground,NaN,pgs,"(Mariners Harbor Playground, 95)",95
1560,Sunrise Playground - PS 195,BROOKLYN,sunrise playground - ps 195,B,Playground,NaN,pgs,"(Playground, 90)",90
1562,Pool - Bronx River Playground,BRONX,pool - bronx river playground,X,Playground,NaN,pgs,"(Playground, 90)",90
1564,Sweetgum Playground,BRONX,sweetgum playground,X,Sweetgum Playground,NaN,pgs,"(Sweetgum Playground, 100)",100
1565,Aqueduct Walk - Rosewood Playground,BRONX,aqueduct walk - rosewood playground,X,Playground,NaN,pgs,"(Playground, 90)",90
1590,Leonardo Ingravallo Playground,QUEENS,leonardo ingravallo playground,Q,Leonardo Ingravallo Playground,NaN,pgs,"(Leonardo Ingravallo Playground, 100)",100
1595,Clawson Playground - PS 50,STATEN ISLAND,clawson playground - ps 50,R,Clawson Playground,NaN,pgs,"(Clawson Playground, 95)",95
1612,Queens Valley Playground - PS 164,BROOKLYN,queens valley playground - ps 164,B,Queens Valley Playground,NaN,pgs,"(Queens Valley Playground, 95)",95
1616,Dr Ronald E McNair Playground,QUEENS,dr ronald e mcnair playground,Q,Dr. Ronald E. McNair Playground,NaN,pgs,"(Dr. Ronald E. McNair Playground, 97)",97
1629,Hallets Point Playground - Area B,QUEENS,hallets point playground - area b,Q,Hallets Point Playground (area B),NaN,pgs,"(Hallets Point Playground (area B), 98)",98
1636,Lie Playground - Real Good Park,QUEENS,lie playground - real good park,Q,PARK,NaN,pgs,"(PARK, 90)",90
1641,Stop and Go Playground,BRONX,stop and go playground,X,Stop nd Go Playground,NaN,pgs,"(Stop nd Go Playground, 98)",98
1650,Catbird Playground,MANHATTAN,catbird playground,M,Catbird Playground,NaN,pgs,"(Catbird Playground, 100)",100
1651,Drumgoole Tot Lot Playground,STATEN ISLAND,drumgoole tot lot playground,R,Playground,NaN,pgs,"(Playground, 90)",90
1652,Starlight Park - Plimpton Playground,BRONX,starlight park - plimpton playground,X,Playground,NaN,pgs,"(Playground, 90)",90
1653,Seaside Playground - PS 225,BROOKLYN,seaside playground - ps 225,B,Playground,NaN,pgs,"(Playground, 90)",90
1655,Castlewood Playground - PS 186,BROOKLYN,castlewood playground - ps 186,B,Castlewood Playground,NaN,pgs,"(Castlewood Playground, 95)",95
1657,Parkside Playground - Bronx,BRONX,parkside playground - bronx,X,Parkside Playground,NaN,pgs,"(Parkside Playground, 95)",95
1659,M L King Houses Playground,MANHATTAN,m l king houses playground,M,Playground,NaN,pgs,"(Playground, 90)",90
1660,Playground Fifty-Two,BRONX,playground fifty-two,X,Playground Fifty-two,NaN,pgs,"(Playground Fifty-two, 100)",100
1664,Under The Tracks Playground,BROOKLYN,under the tracks playground,B,Under The Tracks Playground,NaN,pgs,"(Under The Tracks Playground, 100)",100
1665,La Guardia Playground South,BROOKLYN,la guardia playground south,B,La Guardia Playground South,NaN,pgs,"(La Guardia Playground South, 100)",100
1667,Dyker Playground,STATEN ISLAND,dyker playground,R,Dyker Playground,NaN,pgs,"(Dyker Playground, 100)",100
1668,Playground One-Forty,QUEENS,playground one-forty,Q,Playground One-forty,NaN,pgs,"(Playground One-forty, 100)",100
1677,PS 286 Playground,BROOKLYN,ps 286 playground,B,Ps 286 Playground,NaN,pgs,"(Ps 286 Playground, 100)",100

In [175]:
print 'Recognized:'
print len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)]), '/', len(cParksMatched)

Recognized:
1302 / 1678

## IV. Pools

In [176]:
pools = [x.decode('utf8').lower() for x in pd.read_csv(PARQA + 'data/DPR_property/pools.csv')['Name'].tolist()]

In [177]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('pool'), 'Type'] = 'pool'
# cParksMatched[cParksMatched.Type=='pool']

In [178]:
cParksMatched.ix[cParksMatched.Type=='pool', 'match'] = \
cParksMatched.ix[cParksMatched.Type=='pool', 'cleanName'].apply(lambda x: process.extractOne(x, pools))

In [179]:
cParksMatched.ix[cParksMatched.Type=='pool', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='pool', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='pool', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='pool', 'match'].apply(lambda x: x[1])

In [180]:
cParksMatched[cParksMatched.Type=='pool']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
140,Pool - Metropolitan Avenue,BROOKLYN,pool - metropolitan avenue,B,claremont pool,NaN,pool,"(claremont pool, 85)",85
156,Pool - St. John's Recreation Center,BROOKLYN,pool - st. john's recreation center,B,recreation center 54 pool,NaN,pool,"(recreation center 54 pool, 89)",89
179,Pool - Brownsville Recreation Center,BROOKLYN,pool - brownsville recreation center,B,recreation center 54 pool,NaN,pool,"(recreation center 54 pool, 89)",89
218,Recreation Center - Metropolitan Pool and Fitn...,BROOKLYN,recreation center - metropolitan pool and fitn...,B,metropolitan pool,NaN,pool,"(metropolitan pool, 90)",90
309,Pool - Hansborough,MANHATTAN,pool - hansborough,M,hansborough pool,NaN,pool,"(hansborough pool, 95)",95
352,Pool - JHS 57 and HS 26,BROOKLYN,pool - jhs 57 and hs 26,B,jhs 57/hs 26 pool,NaN,pool,"(jhs 57/hs 26 pool, 95)",95
416,John Jay Park and Pool,MANHATTAN,john jay park and pool,M,claremont pool,NaN,pool,"(claremont pool, 85)",85
482,Williamsbridge Oval - P G Mini Pool and Courts,BRONX,williamsbridge oval - p g mini pool and courts,X,claremont pool,NaN,pool,"(claremont pool, 85)",85
602,Pool - Mullaly,BRONX,pool - mullaly,X,mullaly pool,NaN,pool,"(mullaly pool, 95)",95
614,Pool - Hamilton Fish,MANHATTAN,pool - hamilton fish,M,hamilton fish pool,NaN,pool,"(hamilton fish pool, 95)",95
625,Pool - Mapes,BRONX,pool - mapes,X,mapes pool,NaN,pool,"(mapes pool, 95)",95
655,Pool - Betsy Head Park,BROOKLYN,pool - betsy head park,B,betsy head pool,NaN,pool,"(betsy head pool, 95)",95
656,Pool - Glenwood Houses,BROOKLYN,pool - glenwood houses,B,glenwood houses pool,NaN,pool,"(glenwood houses pool, 95)",95
657,Pool - Fred Douglas,MANHATTAN,pool - fred douglas,M,crotona pool,NaN,pool,"(crotona pool, 85)",85
691,Pool - Dry Dock,MANHATTAN,pool - dry dock,M,dry dock pool,NaN,pool,"(dry dock pool, 95)",95
694,Pool - Abe Lincoln,MANHATTAN,pool - abe lincoln,M,abe lincoln pool,NaN,pool,"(abe lincoln pool, 95)",95
704,Pool - Astoria Park,QUEENS,pool - astoria park,Q,crotona pool,NaN,pool,"(crotona pool, 85)",85
708,Pool - David Fox - PS 251,BROOKLYN,pool - david fox - ps 251,B,david fox/ps 251 pool,NaN,pool,"(david fox/ps 251 pool, 95)",95
716,Pool - Highbridge,MANHATTAN,pool - highbridge,M,highbridge pool,NaN,pool,"(highbridge pool, 95)",95
724,Pool - Wagner,MANHATTAN,pool - wagner,M,wagner pool,NaN,pool,"(wagner pool, 95)",95
728,Pool - Liberty,QUEENS,pool - liberty,Q,liberty pool,NaN,pool,"(liberty pool, 95)",95
729,Pool - Tottenville,STATEN ISLAND,pool - tottenville,R,tottenville pool,NaN,pool,"(tottenville pool, 95)",95
739,Pool - Roy Wilkins,QUEENS,pool - roy wilkins,Q,roy wilkins pool,NaN,pool,"(roy wilkins pool, 95)",95
744,Pool - Faber,STATEN ISLAND,pool - faber,R,faber pool,NaN,pool,"(faber pool, 95)",95
745,Pool - Kosciusko,BROOKLYN,pool - kosciusko,B,kosciuszko pool,NaN,pool,"(kosciuszko pool, 92)",92
771,Pool - John Jay,MANHATTAN,pool - john jay,M,john jay pool,NaN,pool,"(john jay pool, 95)",95
778,Pool - Thomas Jefferson,MANHATTAN,pool - thomas jefferson,M,thomas jefferson pool,NaN,pool,"(thomas jefferson pool, 95)",95
787,Pool - Crotona,BRONX,pool - crotona,X,crotona pool,NaN,pool,"(crotona pool, 95)",95
806,Pool - Claremont,BRONX,pool - claremont,X,claremont pool,NaN,pool,"(claremont pool, 95)",95
808,Pool - Commodore Barry,BROOKLYN,pool - commodore barry,B,commodore barry pool,NaN,pool,"(commodore barry pool, 95)",95
813,Pool - Fisher,QUEENS,pool - fisher,Q,fisher pool,NaN,pool,"(fisher pool, 95)",95
820,Pool - Douglas and Degraw,BROOKLYN,pool - douglas and degraw,B,douglas and degraw pool,NaN,pool,"(douglas and degraw pool, 95)",95
828,Pool - Tompkins Square,MANHATTAN,pool - tompkins square,M,tompkins square pool,NaN,pool,"(tompkins square pool, 95)",95
854,Pool - Jackie Robinson Park,MANHATTAN,pool - jackie robinson park,M,jackie robinson pool,NaN,pool,"(jackie robinson pool, 95)",95
858,Pool - Recreation Center 54,MANHATTAN,pool - recreation center 54,M,recreation center 54 pool,NaN,pool,"(recreation center 54 pool, 95)",95
881,Pool - Marcus Garvey Park,MANHATTAN,pool - marcus garvey park,M,marcus garvey pool,NaN,pool,"(marcus garvey pool, 95)",95
900,Pool - Bushwick,BROOKLYN,pool - bushwick,B,bushwick pool,NaN,pool,"(bushwick pool, 95)",95
906,Pool - Tony Dapolito,MANHATTAN,pool - tony dapolito,M,tony dapolito pool,NaN,pool,"(tony dapolito pool, 95)",95
909,Pool - West Brighton,STATEN ISLAND,pool - west brighton,R,west brighton pool,NaN,pool,"(west brighton pool, 95)",95
912,Pool - Fort Totten,QUEENS,pool - fort totten,Q,fort totten pool,NaN,pool,"(fort totten pool, 95)",95
933,Pool - Lyons,STATEN ISLAND,pool - lyons,R,lyons pool,NaN,pool,"(lyons pool, 95)",95
939,Pool - Sunset Park,BROOKLYN,pool - sunset park,B,sunset park pool,NaN,pool,"(sunset park pool, 95)",95
940,Pool - Howard,BROOKLYN,pool - howard,B,howard pool,NaN,pool,"(howard pool, 95)",95
944,Pool - Haffen,BRONX,pool - haffen,X,haffen pool,NaN,pool,"(haffen pool, 95)",95
1329,Pool - Sheltering Arms Park,MANHATTAN,pool - sheltering arms park,M,sheltering arms pool,NaN,pool,"(sheltering arms pool, 95)",95
1342,Pool - MacArthur,STATEN ISLAND,pool - macarthur,R,mapes pool,NaN,pool,"(mapes pool, 85)",85
1381,Pool - Windmuller,QUEENS,pool - windmuller,Q,windmuller pool,NaN,pool,"(windmuller pool, 95)",95
1384,Pool - Thompson Street,MANHATTAN,pool - thompson street,M,thompson street pool,NaN,pool,"(thompson street pool, 95)",95
1399,Pool - Chelsea,MANHATTAN,pool - chelsea,M,chelsea pool,NaN,pool,"(chelsea pool, 95)",95
1414,Pool - St. Mary's,BRONX,pool - st. mary's,X,st. mary's pool,NaN,pool,"(st. mary's pool, 95)",95
1442,Kosciusko Pool,BROOKLYN,kosciusko pool,B,kosciuszko pool,NaN,pool,"(kosciuszko pool, 97)",97
1485,Pool - McCarren Park,BROOKLYN,pool - mccarren park,B,crotona pool,NaN,pool,"(crotona pool, 85)",85
1495,Pool - Lindower Park,BROOKLYN,pool - lindower park,B,lindower park pool,NaN,pool,"(lindower park pool, 95)",95
1539,Pool - Gertrude Ederle,MANHATTAN,pool - gertrude ederle,M,claremont pool,NaN,pool,"(claremont pool, 85)",85
1557,Pool - PS 10,QUEENS,pool - ps 10,Q,ps 10 pool,NaN,pool,"(ps 10 pool, 95)",95
1558,Pool - Brooklyn Bridge Park Pop-Up,BROOKLYN,pool - brooklyn bridge park pop-up,B,brooklyn bridge park pool,NaN,pool,"(brooklyn bridge park pool, 95)",95
1614,Pool - Marie Curie Park,QUEENS,pool - marie curie park,Q,marie curie park pool,NaN,pool,"(marie curie park pool, 95)",95
1625,Pool - Edenwald Houses,BRONX,pool - edenwald houses,X,edenwald houses pool,NaN,pool,"(edenwald houses pool, 95)",95

In [181]:
print 'Recognized:'
print len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)]), '/', len(cParksMatched)

Recognized:
1360 / 1678

## V. Beaches

In [182]:
beaches = [x.decode('utf8').lower() for x in pd.read_csv(PARQA + 'data/DPR_property/beaches.csv')['Name'].tolist()]

In [183]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('beach'), 'Type'] = 'beach'
# cParksMatched[pd.isnull(cParksMatched.SIGNNAME)]

In [184]:
cParksMatched.ix[cParksMatched.Type=='beach', 'match'] = \
cParksMatched.ix[cParksMatched.Type=='beach', 'cleanName'].apply(lambda x: process.extractOne(x, beaches))

In [185]:
cParksMatched.ix[cParksMatched.Type=='beach', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='beach', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='beach', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='beach', 'match'].apply(lambda x: x[1])

In [186]:
cParksMatched[cParksMatched.Type=='beach']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
117,Beach - Midland,STATEN ISLAND,beach - midland,R,orchard beach and promenade,NaN,beach,"(orchard beach and promenade, 85)",85
196,Beach - Brighton,BROOKLYN,beach - brighton,B,brighton beach,NaN,beach,"(brighton beach, 95)",95
223,Beach - Orchard,BRONX,beach - orchard,X,orchard beach and promenade,NaN,beach,"(orchard beach and promenade, 85)",85
361,Beach - Manhattan,BROOKLYN,beach - manhattan,B,manhattan beach,NaN,beach,"(manhattan beach, 95)",95
648,Beach - Wolfe's Pond,STATEN ISLAND,beach - wolfe's pond,R,wolfe's pond beach,NaN,beach,"(wolfe's pond beach, 95)",95
685,Beach - South,STATEN ISLAND,beach - south,R,south beach,NaN,beach,"(south beach, 95)",95
730,Crescent Beach,STATEN ISLAND,crescent beach,R,orchard beach and promenade,NaN,beach,"(orchard beach and promenade, 85)",85
785,Coney Island Beach and Boardwalk,BROOKLYN,coney island beach and boardwalk,B,coney island and coney island boardwalk,NaN,beach,"(coney island and coney island boardwalk, 95)",95
1029,Golf Course - Dyker Beach,BROOKLYN,golf course - dyker beach,B,manhattan beach,NaN,beach,"(manhattan beach, 85)",85
1217,Orchard Beach Park - Nature Center,BRONX,orchard beach park - nature center,X,manhattan beach,NaN,beach,"(manhattan beach, 85)",85
1298,Beach - Cedar Grove,STATEN ISLAND,beach - cedar grove,R,cedar grove beach,NaN,beach,"(cedar grove beach, 95)",95
1600,Beach - Coney Island,BROOKLYN,beach - coney island,B,coney island and coney island boardwalk,NaN,beach,"(coney island and coney island boardwalk, 85)",85
1603,Beach - Rockaway,QUEENS,beach - rockaway,Q,orchard beach and promenade,NaN,beach,"(orchard beach and promenade, 85)",85

In [187]:
print 'Recognized:'
print len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)]), '/', len(cParksMatched)

Recognized:
1373 / 1678

## VI. School Playgrounds

In [188]:
schools = pd.read_csv(PARQA + 'data/DPR_property/school_playgrounds.csv')['PSID'].tolist()

In [189]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('ps '), 'Type'] = 'school'
# cParksMatched[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('ps')]
# cParksMatched[cParksMatched.cleanName.str.contains('ps')]

In [190]:
cParksMatched.ix[cParksMatched.Type=='school', 'match'] = \
cParksMatched.ix[cParksMatched.Type=='school', 'cleanName'].apply(lambda x: process.extractOne(x, schools))

In [191]:
cParksMatched.ix[cParksMatched.Type=='school', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='school', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='school', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='school', 'match'].apply(lambda x: x[1])

In [192]:
cParksMatched[cParksMatched.Type=='school']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
100,Evergreen Pk - PS 68,QUEENS,evergreen pk - ps 68,Q,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
185,Oakland Gardens - PS 203,QUEENS,oakland gardens - ps 203,Q,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
410,Athens Square - PS 17,QUEENS,athens square - ps 17,Q,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
464,Alfred Smith - PS 1,MANHATTAN,alfred smith - ps 1,M,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
983,Israel Putnam - PS 44,BROOKLYN,israel putnam - ps 44,B,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
1101,Gunn Park - PS 18,QUEENS,gunn park - ps 18,Q,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
1336,Wayanda Park - PS 34,QUEENS,wayanda park - ps 34,Q,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85
1480,PS 4 Paradise Garden,BROOKLYN,ps 4 paradise garden,B,Ps/is 187,NaN,school,"(Ps/is 187, 85)",85

## VII Golf Courses

In [193]:
golfs = [unicode(x).lower() for x in pd.read_csv(PARQA + 'data/DPR_property/DPR_GolfCourses_001.csv')['NAME'].tolist()]

In [194]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME) & cParksMatched.cleanName.str.contains('golf '), 'Type'] = 'golf'

In [196]:
cParksMatched.ix[cParksMatched.Type=='golf', 'match'] = \
cParksMatched.ix[cParksMatched.Type=='golf', 'cleanName'].apply(lambda x: process.extractOne(x, golfs))

In [199]:
cParksMatched.ix[cParksMatched.Type=='golf', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='golf', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='golf', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='golf', 'match'].apply(lambda x: x[1])

In [200]:
cParksMatched[cParksMatched.Type=='golf']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
148,Golf Course - South Shore,STATEN ISLAND,golf course - south shore,R,south shore golf course,NaN,golf,"(south shore golf course, 95)",95
167,Clearview Park and Golf Course,QUEENS,clearview park and golf course,Q,clearview golf course,NaN,golf,"(clearview golf course, 95)",95
310,Golf Course - Kissena,QUEENS,golf course - kissena,Q,kissena park golf course,NaN,golf,"(kissena park golf course, 95)",95
467,Golf Course - Clearview Park,QUEENS,golf course - clearview park,Q,clearview golf course,NaN,golf,"(clearview golf course, 95)",95
495,Golf Course - Silver Lake,STATEN ISLAND,golf course - silver lake,R,silver lake golf course,NaN,golf,"(silver lake golf course, 95)",95
497,Golf Course - Douglaston,QUEENS,golf course - douglaston,Q,douglaston golf course,NaN,golf,"(douglaston golf course, 95)",95
666,Golf Course - Mosholu,BRONX,golf course - mosholu,X,mosholu golf course,NaN,golf,"(mosholu golf course, 95)",95
711,Golf Course - Golden Bear Driving Range,QUEENS,golf course - golden bear driving range,Q,clearview golf course,NaN,golf,"(clearview golf course, 85)",85
815,South Shore Golf Course,STATEN ISLAND,south shore golf course,R,south shore golf course,NaN,golf,"(south shore golf course, 100)",100
1061,Golf Course - Randalls Island Driving Range,MANHATTAN,golf course - randalls island driving range,M,clearview golf course,NaN,golf,"(clearview golf course, 85)",85
1121,Golf Course - LaTourette,STATEN ISLAND,golf course - latourette,R,la tourette golf course,NaN,golf,"(la tourette golf course, 93)",93
1332,Golf Course - Pelham and Split Rock,BRONX,golf course - pelham and split rock,X,clearview golf course,NaN,golf,"(clearview golf course, 85)",85
1449,La Tourette Park and Golf Course,STATEN ISLAND,la tourette park and golf course,R,la tourette golf course,NaN,golf,"(la tourette golf course, 95)",95

In [201]:
print 'Recognized:'
print len(cParksMatched[pd.notnull(cParksMatched.SIGNNAME)]), '/', len(cParksMatched)

Recognized:
1394 / 1678

## VI. Park Names

In [202]:
parkNames = gp.read_file(PARQA + 'data/parks_computed.geojson')[['SIGNNAME','BOROUGH']].drop_duplicates()
parkNames['SIGNNAME'] = parkNames['SIGNNAME'].str.lower()

In [203]:
ofParks = [unicode(x) for x in parkNames['SIGNNAME'].tolist()]

# ofParks = {k:[unicode(x) for x in list(v)] for k,v in parkNames.groupby("BOROUGH")["SIGNNAME"]}

# tmp = []
# for v in ofParks.values():
#     tmp.extend(v)
# ofParks['?'] = tmp   #['???'] ### to mark parks with unspecified Borough

In [204]:
cParksMatched.ix[pd.isnull(cParksMatched.SIGNNAME), 'Type'] = 'other'

In [205]:
### ATTENTION, TAKES ~5 MINUTES

cParksMatched.ix[cParksMatched.Type=='other', 'match'] = \
cParksMatched[cParksMatched.Type=='other'].apply(lambda x: process.extractOne(x.cleanName, ofParks), 1)

In [206]:
cParksMatched.ix[cParksMatched.Type=='other', 'SIGNNAME'] = \
cParksMatched.ix[cParksMatched.Type=='other', 'match'].apply(lambda x: x[0])

cParksMatched.ix[cParksMatched.Type=='other', 'ratio'] = \
cParksMatched.ix[cParksMatched.Type=='other', 'match'].apply(lambda x: x[1])

In [207]:
cParksMatched[cParksMatched.Type=='other']

,Park Facility Name,Borough,cleanName,code,SIGNNAME,BOROUGH,Type,match,ratio
0,Geo Soilan Park - Battery Park City,MANHATTAN,geo soilan park - battery park city,M,battery park city,NaN,other,"(battery park city, 90)",90
8,William H Seward Park,MANHATTAN,william h seward park,M,park,NaN,other,"(park, 90)",90
18,St Catherine's Park,MANHATTAN,st catherine's park,M,st. catherine's park,NaN,other,"(st. catherine's park, 97)",97
35,Louis J Valentino Jr Park and Pier,BROOKLYN,louis j valentino jr park and pier,B,queensbridge park,NaN,other,"(queensbridge park, 85)",85
43,Hells Kitchen Park,MANHATTAN,hells kitchen park,M,hell's kitchen park,NaN,other,"(hell's kitchen park, 97)",97
45,Brooklyn Civic Center Parks,BROOKLYN,brooklyn civic center parks,B,park,NaN,other,"(park, 90)",90
51,J J Byrne Memorial Park,BROOKLYN,j j byrne memorial park,B,park,NaN,other,"(park, 90)",90
57,Sherman Creek Park,MANHATTAN,sherman creek park,M,sherman creek,NaN,other,"(sherman creek, 95)",95
58,Kolbert Park,BROOKLYN,kolbert park,B,park,NaN,other,"(park, 90)",90
77,Alice Kornegay,MANHATTAN,alice kornegay,M,alice kornegay triangle,NaN,other,"(alice kornegay triangle, 90)",90
79,Recreation Center - Thomas Jefferson,MANHATTAN,recreation center - thomas jefferson,M,red hook recreation area,NaN,other,"(red hook recreation area, 85)",85
83,Hillside Park - JHS 172,QUEENS,hillside park - jhs 172,Q,park,NaN,other,"(park, 90)",90
91,Maurice Park,QUEENS,maurice park,Q,park,NaN,other,"(park, 90)",90
101,Blue Heron Park Preserve,STATEN ISLAND,blue heron park preserve,R,park,NaN,other,"(park, 90)",90
105,Recreation Center - Hansborough,MANHATTAN,recreation center - hansborough,M,hansborough recreation center,NaN,other,"(hansborough recreation center, 95)",95
108,Riverside Park - Skate Park,MANHATTAN,riverside park - skate park,M,riverside park,NaN,other,"(riverside park, 90)",90
118,Recreation Center - Fort Hamilton Senior Center,BROOKLYN,recreation center - fort hamilton senior center,B,red hook recreation area,NaN,other,"(red hook recreation area, 85)",85
119,High Line Park,MANHATTAN,high line park,M,park,NaN,other,"(park, 90)",90
136,Recreation Center - Red Hook,BROOKLYN,recreation center - red hook,B,recreation center 54,NaN,other,"(recreation center 54, 87)",87
141,Recreation Center - St. John's,BROOKLYN,recreation center - st. john's,B,st. john's recreation center,NaN,other,"(st. john's recreation center, 95)",95
143,Recreation Center - Chelsea,MANHATTAN,recreation center - chelsea,M,chelsea recreation center,NaN,other,"(chelsea recreation center, 95)",95
149,East River Park,MANHATTAN,east river park,M,park,NaN,other,"(park, 90)",90
150,Weeping Beech - Margaret I Carmen Green,QUEENS,weeping beech - margaret i carmen green,Q,margaret i. carman green - weeping beech,NaN,other,"(margaret i. carman green - weeping beech, 92)",92
161,Bronx River Park,BRONX,bronx river park,X,bronx river parkway,NaN,other,"(bronx river parkway, 91)",91
165,Recreation Center - Brownsville,BROOKLYN,recreation center - brownsville,B,marcy green center,NaN,other,"(marcy green center, 85)",85
171,Rockaway Park,QUEENS,rockaway park,Q,park,NaN,other,"(park, 90)",90
172,Riverside Park - Running Track and 78th St Bal...,MANHATTAN,riverside park - running track and 78th st bal...,M,riverside park,NaN,other,"(riverside park, 90)",90
173,Wright Brothers Park,MANHATTAN,wright brothers park,M,park,NaN,other,"(park, 90)",90
183,Monsignor Mcgolrick Park,BROOKLYN,monsignor mcgolrick park,B,park,NaN,other,"(park, 90)",90
189,J Hood Wright Park,MANHATTAN,j hood wright park,M,j. hood wright park,NaN,other,"(j. hood wright park, 97)",97
...,...,...,...,...,...,...,...,...,...
1527,Park Strip,BROOKLYN,park strip,B,park,NaN,other,"(park, 90)",90
1528,Hunter's Point Park,QUEENS,hunter's point park,Q,hunter's point south park,NaN,other,"(hunter's point south park, 95)",95
1531,McCarren Park Ice Skating Rink,BROOKLYN,mccarren park ice skating rink,B,park,NaN,other,"(park, 90)",90
1550,Riverbank State Park,MANHATTAN,riverbank state park,M,park,NaN,other,"(park, 90)",90
1568,Riverside Park - Baseball Fields,QUEENS,riverside park - baseball fields,Q,riverside park,NaN,other,"(riverside park, 90)",90
1569,Roberto Clemente State Park,BRONX,roberto clemente state park,X,park,NaN,other,"(park, 90)",90
1570,Kosciusko Street Garden,BROOKLYN,kosciusko street garden,B,kosciuszko street garden,NaN,other,"(kosciuszko street garden, 98)",98
1580,West 87th Street Garden,MANHATTAN,west 87th street garden,M,w 87th street garden,NaN,other,"(w 87th street garden, 93)",93
1582,I Am Park,BRONX,i am park,X,i-am-park,NaN,other,"(i-am-park, 100)",100
1583,Aqueduct Walk - Frisch Field In Bronx Park,BRONX,aqueduct walk - frisch field in bronx park,X,bronx park,NaN,other,"(bronx park, 90)",90
1585,Recreation Center - A.R.R.O.W.,QUEENS,recreation center - a.r.r.o.w.,Q,recreation center 54,NaN,other,"(recreation center 54, 87)",87
1587,Metro North Community Gardens,QUEENS,metro north community gardens,Q,unity gardens,NaN,other,"(unity gardens, 90)",90
1591,Recreation Center - Highbridge,MANHATTAN,recreation center - highbridge,M,highbridge park,NaN,other,"(highbridge park, 85)",85
1597,Weeping Beech - Margaret I Carmen Green,MANHATTAN,weeping beech - margaret i carmen green,M,margaret i. carman green - weeping beech,NaN,other,"(margaret i. carman green - weeping beech, 92)",92
1602,St Nicholas - Olive St Garden,BROOKLYN,st nicholas - olive st garden,B,st. nicholas - olive st. garden,NaN,other,"(st. nicholas - olive st. garden, 97)",97
1605,Risse St Park,BRONX,risse st park,X,park,NaN,other,"(park, 90)",90
1617,Alley Pond Park - Nature Center,NaN,alley pond park - nature center,NaN,park,NaN,other,"(park, 90)",90
1618,Hook Creek Marsh,QUEENS,hook creek marsh,Q,red hook recreation area,NaN,other,"(red hook recreation area, 85)",85
1623,St Nicholas - Powers St Garden,BROOKLYN,st nicholas - powers st garden,B,st. nicholas - powers st. garden,NaN,other,"(st. nicholas - powers st. garden, 97)",97
1626,Hendrick I Lott House,BROOKLYN,hendrick i lott house,B,hendrick i. lott house,NaN,other,"(hendrick i. lott house, 98)",98
1627,William H Seward Park,BROOKLYN,william h seward park,B,park,NaN,other,"(park, 90)",90
1630,Recreation Center - Betsy Head CBO- Amboy Neig...,BROOKLYN,recreation center - betsy head cbo- amboy neig...,B,amboy neighborhood center,NaN,other,"(amboy neighborhood center, 90)",90
1642,El Puente - Earth Spirit Garden,BROOKLYN,el puente - earth spirit garden,B,earth spirit garden,NaN,other,"(earth spirit garden, 90)",90
1649,Starlight Park - Peace Park,BRONX,starlight park - peace park,X,starlight park,NaN,other,"(starlight park, 90)",90
1656,A Child's Place,BROOKLYN,a child's place,B,hunter's point south park,NaN,other,"(hunter's point south park, 85)",85
1662,Recreation Area,MANHATTAN,recreation area,M,recreational area,NaN,other,"(recreational area, 94)",94
1670,Hunt's Point Riverside Park,MANHATTAN,hunt's point riverside park,M,hunts point riverside park,NaN,other,"(hunts point riverside park, 98)",98
1673,West 104th Street Garden,MANHATTAN,west 104th street garden,M,w 104th street garden,NaN,other,"(w 104th street garden, 93)",93
1674,Recreation Center - Haffen Park,BRONX,recreation center - haffen park,X,haffen park,NaN,other,"(haffen park, 90)",90
1675,New Ballfield,STATEN ISLAND,new ballfield,R,william f. passannante ballfield,NaN,other,"(william f. passannante ballfield, 85)",85

In [208]:
cParksMatched.to_csv(PARQA + 'data/311/Ontology2_unverified.csv',encoding='utf8')